project:
  type: default
  execute-dir: project

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    embed-resources: true
    page-layout: full
    fig-width: 10
    fig-height: 6
    fig-dpi: 300
    df-print: paged
    smooth-scroll: true
    link-external-newwindow: true
    echo: false
    
crossref:
  fig-title: "Figure"
  tbl-title: "Table"
  fig-prefix: "Figure"
  tbl-prefix: "Table"