# This file was generated by the {rix} R package v0.16.0 on 2025-07-11
# with following call:
# >rix(date = "2025-07-07",
#  > r_pkgs = c("R_utils",
#  > "archive",
#  > "crosstalk",
#  > "dplyr",
#  > "DT",
#  > "ggplot2",
#  > "ggrepel",
#  > "forcats",
#  > "httr",
#  > "htmltools",
#  > "janitor",
#  > "jsonlite",
#  > "lubridate",
#  > "openalexR",
#  > "purrr",
#  > "quarto",
#  > "readr",
#  > "readxl",
#  > "rix",
#  > "tidyr",
#  > "tinytable",
#  > "xml2"),
#  > system_pkgs = c("air-formatter",
#  > "quarto",
#  > "typst",
#  > "which"),
#  > git_pkgs = list(list(package_name = "rixpress",
#  > repo_url = "https://github.com/b-rodrigues/rixpress",
#  > commit = "fe0a9a2eeede61984845e04c9f7cc7a152e3aebf")),
#  > ide = "none",
#  > project_path = ".",
#  >      overwrite = TRUE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-07-07.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      archive
      crosstalk
      dplyr
      DT
      forcats
      ggplot2
      ggrepel
      htmltools
      httr
      janitor
      jsonlite
      lubridate
      openalexR
      purrr
      quarto
      R_utils
      readr
      readxl
      rix
      tidyr
      tinytable
      xml2;
  };
 
    rixpress = (pkgs.rPackages.buildRPackage {
      name = "rixpress";
      src = pkgs.fetchgit {
        url = "https://github.com/b-rodrigues/rixpress";
        rev = "fe0a9a2eeede61984845e04c9f7cc7a152e3aebf";
        sha256 = "sha256-BNWp9ldMPlhBxCEs3O2RUCrrkhJLNgIBBHb345oIRRY=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          igraph
          jsonlite
          processx;
      };
    });
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      air-formatter
      glibcLocales
      nix
      quarto
      R
      typst
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rixpress rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
