# This file was generated by the {rix} R package v0.15.5 on 2025-07-10
# with following call:
# >rix(date = "2025-07-07",
#  > r_pkgs = c("R_utils",
#  > "archive",
#  > "crosstalk",
#  > "dplyr",
#  > "DT",
#  > "ggplot2",
#  > "httr",
#  > "htmltools",
#  > "janitor",
#  > "jsonlite",
#  > "lubridate",
#  > "openalexR",
#  > "plotly",
#  > "purrr",
#  > "quarto",
#  > "readr",
#  > "readxl",
#  > "rix",
#  > "tarchetypes",
#  > "targets",
#  > "tidyjson",
#  > "tidyr",
#  > "tinytable",
#  > "xml2"),
#  > system_pkgs = c("air-formatter",
#  > "quarto",
#  > "typst"),
#  > git_pkgs = list(list(package_name = "rixpress",
#  > repo_url = "https://github.com/b-rodrigues/rixpress",
#  > commit = "dfef00af24b43aabbcf26efe61b3fb72d4a89bd9")),
#  >      ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-07-07.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      archive
      crosstalk
      dplyr
      DT
      ggplot2
      htmltools
      httr
      janitor
      jsonlite
      lubridate
      openalexR
      plotly
      purrr
      quarto
      R_utils
      readr
      readxl
      rix
      tarchetypes
      targets
      tidyjson
      tidyr
      tinytable
      xml2;
  };
 
    rixpress = (pkgs.rPackages.buildRPackage {
      name = "rixpress";
      src = pkgs.fetchgit {
        url = "https://github.com/b-rodrigues/rixpress";
        rev = "dfef00af24b43aabbcf26efe61b3fb72d4a89bd9";
        sha256 = "sha256-bTaSEQXjWO/F2riQK0lS3R6PNNyNpUcZPzp9qEVEA00=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          igraph
          jsonlite
          processx;
      };
    });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      air-formatter
      glibcLocales
      nix
      quarto
      R
      typst;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ rixpress rpkgs  system_packages   ];
  
}
