version = 1
SPDX-PackageName = "research_outputs_analysis"
SPDX-PackageSupplier = "Bruno Rodrigues <bruno.rodrigues@mesr.etat.lu>"
SPDX-PackageDownloadLocation = "https://github.com/b-rodrigues/research_outputs_analysis"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Bruno Rodrigues"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = "report/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Bruno Rodrigues"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
